-- -----------------------------------------------------
-- Schema full-stack-ecommerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `full-stack-ecommerce`;

CREATE SCHEMA `full-stack-ecommerce`;
USE `full-stack-ecommerce` ;

-- -----------------------------------------------------
-- Table `full-stack-ecommerce`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `full-stack-ecommerce`.`product_category` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Table `full-stack-ecommerce`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `full-stack-ecommerce`.`product` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `sku` VARCHAR(255) DEFAULT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `description` VARCHAR(255) DEFAULT NULL,
  `unit_price` DECIMAL(13,2) DEFAULT NULL,
  `image_url` VARCHAR(255) DEFAULT NULL,
  `active` BIT DEFAULT 1,
  `units_in_stock` INT(11) DEFAULT NULL,
  `date_created` DATETIME(6) DEFAULT NULL,
  `last_updated` DATETIME(6) DEFAULT NULL,
  `category_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_category` (`category_id`),
  CONSTRAINT `fk_category` FOREIGN KEY (`category_id`) REFERENCES `product_category` (`id`)
) 
ENGINE=InnoDB
AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Categories
-- -----------------------------------------------------
INSERT INTO product_category(CATEGORY_NAME) VALUES ('Smartphones');
INSERT INTO product_category(CATEGORY_NAME) VALUES ('Laptops');
INSERT INTO product_category(CATEGORY_NAME) VALUES ('Keyboards');
INSERT INTO product_category(CATEGORY_NAME) VALUES ('Mice');
INSERT INTO product_category(CATEGORY_NAME) VALUES ('Monitors');
INSERT INTO product_category(CATEGORY_NAME) VALUES ('Printers');
-- -----------------------------------------------------
-- Laptops
-- -----------------------------------------------------
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LAPTOP-1000', 'Laptop - Express', 	'Powered by a 10th Gen Intel Core i7 processor with integrated Intel graphics, the notebook is ready for work or play with over 12 hours of battery life.', 'assets/images/products/laptops/laptop-1000.png', 1, 210, 1220, 2, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LAPTOP-1001', 'Laptop - Cherokee',	'Powered by a 10th Gen Intel Core i7 processor with integrated Intel graphics, the notebook is ready for work or play with over 12 hours of battery life.', 'assets/images/products/laptops/laptop-1001.png', 1, 005, 2310, 2, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LAPTOP-1002', 'Laptop - Sweeper', 	'Powered by a 10th Gen Intel Core i7 processor with integrated Intel graphics, the notebook is ready for work or play with over 12 hours of battery life.', 'assets/images/products/laptops/laptop-1002.png', 1, 009, 1225, 2, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LAPTOP-1003', 'Laptop - Aspire', 	'Powered by a 10th Gen Intel Core i7 processor with integrated Intel graphics, the notebook is ready for work or play with over 12 hours of battery life.', 'assets/images/products/laptops/laptop-1003.png', 1, 104, 3422, 2, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LAPTOP-1004', 'Laptop - Dorian', 	'Powered by a 10th Gen Intel Core i7 processor with integrated Intel graphics, the notebook is ready for work or play with over 12 hours of battery life.', 'assets/images/products/laptops/laptop-1004.png', 1, 130, 1221, 2, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LAPTOP-1005', 'Laptop - Columbia', 	'Powered by a 10th Gen Intel Core i7 processor with integrated Intel graphics, the notebook is ready for work or play with over 12 hours of battery life.', 'assets/images/products/laptops/laptop-1005.png', 1, 008, 2311, 2, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LAPTOP-1006', 'Laptop - Worthing', 	'Powered by a 10th Gen Intel Core i7 processor with integrated Intel graphics, the notebook is ready for work or play with over 12 hours of battery life.', 'assets/images/products/laptops/laptop-1006.png', 1, 230, 2122, 2, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LAPTOP-1007', 'Laptop - Oak Cliff', 'Powered by a 10th Gen Intel Core i7 processor with integrated Intel graphics, the notebook is ready for work or play with over 12 hours of battery life.', 'assets/images/products/laptops/laptop-1007.png', 1, 102, 2236, 2, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LAPTOP-1008', 'Laptop - Tachyon', 	'Powered by a 10th Gen Intel Core i7 processor with integrated Intel graphics, the notebook is ready for work or play with over 12 hours of battery life.', 'assets/images/products/laptops/laptop-1008.png', 1, 103, 2347, 2, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LAPTOP-1009', 'Laptop - Pan', 		'Powered by a 10th Gen Intel Core i7 processor with integrated Intel graphics, the notebook is ready for work or play with over 12 hours of battery life.', 'assets/images/products/laptops/laptop-1009.png', 1, 004, 1527, 2, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LAPTOP-1010', 'Laptop - Phase', 	'Powered by a 10th Gen Intel Core i7 processor with integrated Intel graphics, the notebook is ready for work or play with over 12 hours of battery life.', 'assets/images/products/laptops/laptop-1010.png', 1, 104, 1235, 2, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LAPTOP-1011', 'Laptop - Falling', 	'Powered by a 10th Gen Intel Core i7 processor with integrated Intel graphics, the notebook is ready for work or play with over 12 hours of battery life.', 'assets/images/products/laptops/laptop-1011.png', 1, 150, 2548, 2, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LAPTOP-1012', 'Laptop - Wispy', 	'Powered by a 10th Gen Intel Core i7 processor with integrated Intel graphics, the notebook is ready for work or play with over 12 hours of battery life.', 'assets/images/products/laptops/laptop-1012.png', 1, 104, 2247, 2, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LAPTOP-1013', 'Laptop - Arlington', 'Powered by a 10th Gen Intel Core i7 processor with integrated Intel graphics, the notebook is ready for work or play with over 12 hours of battery life.', 'assets/images/products/laptops/laptop-1013.png', 1, 105, 2538, 2, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LAPTOP-1014', 'Laptop - Gazing', 	'Powered by a 10th Gen Intel Core i7 processor with integrated Intel graphics, the notebook is ready for work or play with over 12 hours of battery life.', 'assets/images/products/laptops/laptop-1014.png', 1, 103, 2351, 2, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LAPTOP-1015', 'Laptop - Azura', 	'Powered by a 10th Gen Intel Core i7 processor with integrated Intel graphics, the notebook is ready for work or play with over 12 hours of battery life.', 'assets/images/products/laptops/laptop-1015.png', 1, 102, 2349, 2, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LAPTOP-1016', 'Laptop - Quantum', 	'Powered by a 10th Gen Intel Core i7 processor with integrated Intel graphics, the notebook is ready for work or play with over 12 hours of battery life.', 'assets/images/products/laptops/laptop-1016.png', 1, 104, 1348, 2, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LAPTOP-1017', 'Laptop - Light Year','Powered by a 10th Gen Intel Core i7 processor with integrated Intel graphics, the notebook is ready for work or play with over 12 hours of battery life.', 'assets/images/products/laptops/laptop-1017.png', 1, 102, 1345, 2, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LAPTOP-1018', 'Laptop - Taylor', 	'Powered by a 10th Gen Intel Core i7 processor with integrated Intel graphics, the notebook is ready for work or play with over 12 hours of battery life.', 'assets/images/products/laptops/laptop-1018.png', 1, 105, 1023, 2, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LAPTOP-1019', 'Laptop - Gracia', 	'Powered by a 10th Gen Intel Core i7 processor with integrated Intel graphics, the notebook is ready for work or play with over 12 hours of battery life.', 'assets/images/products/laptops/laptop-1019.png', 1, 104, 1631, 2, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LAPTOP-1020', 'Laptop - Relax', 	'Powered by a 10th Gen Intel Core i7 processor with integrated Intel graphics, the notebook is ready for work or play with over 12 hours of battery life.', 'assets/images/products/laptops/laptop-1020.png', 1, 103, 1455, 2, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LAPTOP-1021', 'Laptop - Windermere','Powered by a 10th Gen Intel Core i7 processor with integrated Intel graphics, the notebook is ready for work or play with over 12 hours of battery life.', 'assets/images/products/laptops/laptop-1021.png', 1, 102, 1347, 2, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LAPTOP-1022', 'Laptop - Prancer', 	'Powered by a 10th Gen Intel Core i7 processor with integrated Intel graphics, the notebook is ready for work or play with over 12 hours of battery life.', 'assets/images/products/laptops/laptop-1022.png', 1, 104, 2238, 2, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LAPTOP-1023', 'Laptop - Recursion', 'Powered by a 10th Gen Intel Core i7 processor with integrated Intel graphics, the notebook is ready for work or play with over 12 hours of battery life.', 'assets/images/products/laptops/laptop-1023.png', 1, 005, 2566, 2, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('LAPTOP-1024', 'Laptop - Treasure', 	'Powered by a 10th Gen Intel Core i7 processor with integrated Intel graphics, the notebook is ready for work or play with over 12 hours of battery life.', 'assets/images/products/laptops/laptop-1024.png', 1, 034, 1236, 2, NOW());

-- -----------------------------------------------------
-- Smartphone
-- -----------------------------------------------------
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('SMARTPHONE-1000', 'Smartphone - Express', 	'Our smartphone has an all-screen design, Liquid Retina display, TrueDepth camera, Face ID and A12 Bionic.It is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and eSIM cards.', 'assets/images/products/smartphones/smartphone-1000.png', 1, 210, 1220, 1, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('SMARTPHONE-1001', 'Smartphone - Cherokee',	'Our smartphone has an all-screen design, Liquid Retina display, TrueDepth camera, Face ID and A12 Bionic.It is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and eSIM cards.', 'assets/images/products/smartphones/smartphone-1001.png', 1, 005, 1310, 1, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('SMARTPHONE-1002', 'Smartphone - Sweeper', 	'Our smartphone has an all-screen design, Liquid Retina display, TrueDepth camera, Face ID and A12 Bionic.It is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and eSIM cards.', 'assets/images/products/smartphones/smartphone-1002.png', 1, 009, 1225, 1, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('SMARTPHONE-1003', 'Smartphone - Aspire', 	'Our smartphone has an all-screen design, Liquid Retina display, TrueDepth camera, Face ID and A12 Bionic.It is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and eSIM cards.', 'assets/images/products/smartphones/smartphone-1003.png', 1, 104, 1422, 1, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('SMARTPHONE-1004', 'Smartphone - Dorian', 	'Our smartphone has an all-screen design, Liquid Retina display, TrueDepth camera, Face ID and A12 Bionic.It is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and eSIM cards.', 'assets/images/products/smartphones/smartphone-1004.png', 1, 130, 1221, 1, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('SMARTPHONE-1005', 'Smartphone - Columbia', 	'Our smartphone has an all-screen design, Liquid Retina display, TrueDepth camera, Face ID and A12 Bionic.It is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and eSIM cards.', 'assets/images/products/smartphones/smartphone-1005.png', 1, 008, 1311, 1, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('SMARTPHONE-1006', 'Smartphone - Worthing', 	'Our smartphone has an all-screen design, Liquid Retina display, TrueDepth camera, Face ID and A12 Bionic.It is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and eSIM cards.', 'assets/images/products/smartphones/smartphone-1006.png', 1, 230, 1122, 1, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('SMARTPHONE-1007', 'Smartphone - Oak Cliff', 'Our smartphone has an all-screen design, Liquid Retina display, TrueDepth camera, Face ID and A12 Bionic.It is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and eSIM cards.', 'assets/images/products/smartphones/smartphone-1007.png', 1, 102, 1236, 1, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('SMARTPHONE-1008', 'Smartphone - Tachyon', 	'Our smartphone has an all-screen design, Liquid Retina display, TrueDepth camera, Face ID and A12 Bionic.It is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and eSIM cards.', 'assets/images/products/smartphones/smartphone-1008.png', 1, 103, 1347, 1, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('SMARTPHONE-1009', 'Smartphone - Pan', 		'Our smartphone has an all-screen design, Liquid Retina display, TrueDepth camera, Face ID and A12 Bionic.It is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and eSIM cards.', 'assets/images/products/smartphones/smartphone-1009.png', 1, 004, 1527, 1, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('SMARTPHONE-1010', 'Smartphone - Phase', 	'Our smartphone has an all-screen design, Liquid Retina display, TrueDepth camera, Face ID and A12 Bionic.It is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and eSIM cards.', 'assets/images/products/smartphones/smartphone-1010.png', 1, 104, 1235, 1, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('SMARTPHONE-1011', 'Smartphone - Falling', 	'Our smartphone has an all-screen design, Liquid Retina display, TrueDepth camera, Face ID and A12 Bionic.It is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and eSIM cards.', 'assets/images/products/smartphones/smartphone-1011.png', 1, 150, 1548, 1, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('SMARTPHONE-1012', 'Smartphone - Wispy', 	'Our smartphone has an all-screen design, Liquid Retina display, TrueDepth camera, Face ID and A12 Bionic.It is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and eSIM cards.', 'assets/images/products/smartphones/smartphone-1012.png', 1, 004, 1247, 1, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('SMARTPHONE-1013', 'Smartphone - Arlington', 'Our smartphone has an all-screen design, Liquid Retina display, TrueDepth camera, Face ID and A12 Bionic.It is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and eSIM cards.', 'assets/images/products/smartphones/smartphone-1013.png', 1, 105, 1538, 1, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('SMARTPHONE-1014', 'Smartphone - Gazing', 	'Our smartphone has an all-screen design, Liquid Retina display, TrueDepth camera, Face ID and A12 Bionic.It is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and eSIM cards.', 'assets/images/products/smartphones/smartphone-1014.png', 1, 103, 1351, 1, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('SMARTPHONE-1015', 'Smartphone - Azura', 	'Our smartphone has an all-screen design, Liquid Retina display, TrueDepth camera, Face ID and A12 Bionic.It is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and eSIM cards.', 'assets/images/products/smartphones/smartphone-1015.png', 1, 102, 1349, 1, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('SMARTPHONE-1016', 'Smartphone - Quantum', 	'Our smartphone has an all-screen design, Liquid Retina display, TrueDepth camera, Face ID and A12 Bionic.It is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and eSIM cards.', 'assets/images/products/smartphones/smartphone-1016.png', 1, 004, 1348, 1, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('SMARTPHONE-1017', 'Smartphone - Light Year','Our smartphone has an all-screen design, Liquid Retina display, TrueDepth camera, Face ID and A12 Bionic.It is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and eSIM cards.', 'assets/images/products/smartphones/smartphone-1017.png', 1, 102, 1345, 1, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('SMARTPHONE-1018', 'Smartphone - Taylor', 	'Our smartphone has an all-screen design, Liquid Retina display, TrueDepth camera, Face ID and A12 Bionic.It is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and eSIM cards.', 'assets/images/products/smartphones/smartphone-1018.png', 1, 105, 1023, 1, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('SMARTPHONE-1019', 'Smartphone - Gracia', 	'Our smartphone has an all-screen design, Liquid Retina display, TrueDepth camera, Face ID and A12 Bionic.It is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and eSIM cards.', 'assets/images/products/smartphones/smartphone-1019.png', 1, 104, 1631, 1, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('SMARTPHONE-1020', 'Smartphone - Relax', 	'Our smartphone has an all-screen design, Liquid Retina display, TrueDepth camera, Face ID and A12 Bionic.It is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and eSIM cards.', 'assets/images/products/smartphones/smartphone-1020.png', 1, 003, 1455, 1, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('SMARTPHONE-1021', 'Smartphone - Windermere','Our smartphone has an all-screen design, Liquid Retina display, TrueDepth camera, Face ID and A12 Bionic.It is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and eSIM cards.', 'assets/images/products/smartphones/smartphone-1021.png', 1, 102, 1347, 1, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('SMARTPHONE-1022', 'Smartphone - Prancer', 	'Our smartphone has an all-screen design, Liquid Retina display, TrueDepth camera, Face ID and A12 Bionic.It is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and eSIM cards.', 'assets/images/products/smartphones/smartphone-1022.png', 1, 104, 1238, 1, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('SMARTPHONE-1023', 'Smartphone - Recursion', 'Our smartphone has an all-screen design, Liquid Retina display, TrueDepth camera, Face ID and A12 Bionic.It is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and eSIM cards.', 'assets/images/products/smartphones/smartphone-1023.png', 1, 005, 1566, 1, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('SMARTPHONE-1024', 'Smartphone - Treasure', 	'Our smartphone has an all-screen design, Liquid Retina display, TrueDepth camera, Face ID and A12 Bionic.It is a dual-SIM (GSM and GSM) smartphone that accepts Nano-SIM and eSIM cards.', 'assets/images/products/smartphones/smartphone-1024.png', 1, 034, 1236, 1, NOW());


-- -----------------------------------------------------
-- Keyboards
-- -----------------------------------------------------
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('KEYBOARDS-1000', 'Keyboard - Express', 	  'Keyboard with a compact design that still features a full-sized keyboard and number pad, our keyboard is ideal for home and office environments. Comes with 1 year warrenty.', 'assets/images/products/keyboards/keyboard-1000.png', 1, 210, 12.99, 3, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('KEYBOARDS-1001', 'Keyboard - Cherokee',	  'Keyboard with a compact design that still features a full-sized keyboard and number pad, our keyboard is ideal for home and office environments. Comes with 1 year warrenty.', 'assets/images/products/keyboards/keyboard-1001.png', 1, 005, 13.99, 3, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('KEYBOARDS-1002', 'Keyboard - Sweeper', 	  'Keyboard with a compact design that still features a full-sized keyboard and number pad, our keyboard is ideal for home and office environments. Comes with 1 year warrenty.', 'assets/images/products/keyboards/keyboard-1002.png', 1, 009, 12.99, 3, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('KEYBOARDS-1003', 'Keyboard - Aspire', 	  'Keyboard with a compact design that still features a full-sized keyboard and number pad, our keyboard is ideal for home and office environments. Comes with 1 year warrenty.', 'assets/images/products/keyboards/keyboard-1003.png', 1, 104, 14.99, 3, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('KEYBOARDS-1004', 'Keyboard - Dorian', 	  'Keyboard with a compact design that still features a full-sized keyboard and number pad, our keyboard is ideal for home and office environments. Comes with 1 year warrenty.', 'assets/images/products/keyboards/keyboard-1004.png', 1, 130, 12.99, 3, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('KEYBOARDS-1005', 'Keyboard - Columbia',   'Keyboard with a compact design that still features a full-sized keyboard and number pad, our keyboard is ideal for home and office environments. Comes with 1 year warrenty.', 'assets/images/products/keyboards/keyboard-1005.png', 1, 008, 13.99, 3, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('KEYBOARDS-1006', 'Keyboard - Worthing',   'Keyboard with a compact design that still features a full-sized keyboard and number pad, our keyboard is ideal for home and office environments. Comes with 1 year warrenty.', 'assets/images/products/keyboards/keyboard-1006.png', 1, 230, 11.99, 3, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('KEYBOARDS-1007', 'Keyboard - Oak Cliff',  'Keyboard with a compact design that still features a full-sized keyboard and number pad, our keyboard is ideal for home and office environments. Comes with 1 year warrenty.', 'assets/images/products/keyboards/keyboard-1007.png', 1, 102, 12.99, 3, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('KEYBOARDS-1008', 'Keyboard - Tachyon', 	  'Keyboard with a compact design that still features a full-sized keyboard and number pad, our keyboard is ideal for home and office environments. Comes with 1 year warrenty.', 'assets/images/products/keyboards/keyboard-1008.png', 1, 103, 13.99, 3, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('KEYBOARDS-1009', 'Keyboard - Pan', 		  'Keyboard with a compact design that still features a full-sized keyboard and number pad, our keyboard is ideal for home and office environments. Comes with 1 year warrenty.', 'assets/images/products/keyboards/keyboard-1009.png', 1, 004, 15.99, 3, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('KEYBOARDS-1010', 'Keyboard - Phase', 	  'Keyboard with a compact design that still features a full-sized keyboard and number pad, our keyboard is ideal for home and office environments. Comes with 1 year warrenty.', 'assets/images/products/keyboards/keyboard-1010.png', 1, 104, 12.99, 3, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('KEYBOARDS-1011', 'Keyboard - Falling', 	  'Keyboard with a compact design that still features a full-sized keyboard and number pad, our keyboard is ideal for home and office environments. Comes with 1 year warrenty.', 'assets/images/products/keyboards/keyboard-1011.png', 1, 150, 15.99, 3, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('KEYBOARDS-1012', 'Keyboard - Wispy', 	  'Keyboard with a compact design that still features a full-sized keyboard and number pad, our keyboard is ideal for home and office environments. Comes with 1 year warrenty.', 'assets/images/products/keyboards/keyboard-1012.png', 1, 004, 12.99, 3, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('KEYBOARDS-1013', 'Keyboard - Arlington',  'Keyboard with a compact design that still features a full-sized keyboard and number pad, our keyboard is ideal for home and office environments. Comes with 1 year warrenty.', 'assets/images/products/keyboards/keyboard-1013.png', 1, 105, 15.99, 3, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('KEYBOARDS-1014', 'Keyboard - Gazing', 	  'Keyboard with a compact design that still features a full-sized keyboard and number pad, our keyboard is ideal for home and office environments. Comes with 1 year warrenty.', 'assets/images/products/keyboards/keyboard-1014.png', 1, 103, 13.99, 3, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('KEYBOARDS-1015', 'Keyboard - Azura', 	  'Keyboard with a compact design that still features a full-sized keyboard and number pad, our keyboard is ideal for home and office environments. Comes with 1 year warrenty.', 'assets/images/products/keyboards/keyboard-1015.png', 1, 102, 13.99, 3, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('KEYBOARDS-1016', 'Keyboard - Quantum', 	  'Keyboard with a compact design that still features a full-sized keyboard and number pad, our keyboard is ideal for home and office environments. Comes with 1 year warrenty.', 'assets/images/products/keyboards/keyboard-1016.png', 1, 004, 13.99, 3, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('KEYBOARDS-1017', 'Keyboard - LightYear',  'Keyboard with a compact design that still features a full-sized keyboard and number pad, our keyboard is ideal for home and office environments. Comes with 1 year warrenty.', 'assets/images/products/keyboards/keyboard-1017.png', 1, 102, 13.99, 3, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('KEYBOARDS-1018', 'Keyboard - Taylor', 	  'Keyboard with a compact design that still features a full-sized keyboard and number pad, our keyboard is ideal for home and office environments. Comes with 1 year warrenty.', 'assets/images/products/keyboards/keyboard-1018.png', 1, 105, 10.99, 3, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('KEYBOARDS-1019', 'Keyboard - Gracia', 	  'Keyboard with a compact design that still features a full-sized keyboard and number pad, our keyboard is ideal for home and office environments. Comes with 1 year warrenty.', 'assets/images/products/keyboards/keyboard-1019.png', 1, 104, 16.99, 3, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('KEYBOARDS-1020', 'Keyboard - Relax', 	  'Keyboard with a compact design that still features a full-sized keyboard and number pad, our keyboard is ideal for home and office environments. Comes with 1 year warrenty.', 'assets/images/products/keyboards/keyboard-1020.png', 1, 003, 14.99, 3, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('KEYBOARDS-1021', 'Keyboard - Windermer',  'Keyboard with a compact design that still features a full-sized keyboard and number pad, our keyboard is ideal for home and office environments. Comes with 1 year warrenty.', 'assets/images/products/keyboards/keyboard-1021.png', 1, 102, 13.99, 3, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('KEYBOARDS-1022', 'Keyboard - Prancer', 	  'Keyboard with a compact design that still features a full-sized keyboard and number pad, our keyboard is ideal for home and office environments. Comes with 1 year warrenty.', 'assets/images/products/keyboards/keyboard-1022.png', 1, 104, 12.99, 3, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('KEYBOARDS-1023', 'Keyboard - Recursion',  'Keyboard with a compact design that still features a full-sized keyboard and number pad, our keyboard is ideal for home and office environments. Comes with 1 year warrenty.', 'assets/images/products/keyboards/keyboard-1023.png', 1, 005, 15.99, 3, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('KEYBOARDS-1024', 'Keyboard - Treasure',   'Keyboard with a compact design that still features a full-sized keyboard and number pad, our keyboard is ideal for home and office environments. Comes with 1 year warrenty.', 'assets/images/products/keyboards/keyboard-1024.png', 1, 034, 12.99, 3, NOW());


-- -----------------------------------------------------
-- Mice
-- -----------------------------------------------------
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MICE-1000', 'Mice - Express', 	  'Our mouse sensor delivers incredible accuracy, tracking speed and consistency for better control no matter your style of gameplay. Mouse can be used directly out-of-the-box.', 'assets/images/products/mice/mice-1000.png', 1, 210, 12.99, 4, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MICE-1001', 'Mice - Cherokee',	  'Our mouse sensor delivers incredible accuracy, tracking speed and consistency for better control no matter your style of gameplay. Mouse can be used directly out-of-the-box.', 'assets/images/products/mice/mice-1001.png', 1, 005, 13.99, 4, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MICE-1002', 'Mice - Sweeper', 	  'Our mouse sensor delivers incredible accuracy, tracking speed and consistency for better control no matter your style of gameplay. Mouse can be used directly out-of-the-box.', 'assets/images/products/mice/mice-1002.png', 1, 009, 12.99, 4, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MICE-1003', 'Mice - Aspire', 	  'Our mouse sensor delivers incredible accuracy, tracking speed and consistency for better control no matter your style of gameplay. Mouse can be used directly out-of-the-box.', 'assets/images/products/mice/mice-1003.png', 1, 104, 14.99, 4, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MICE-1004', 'Mice - Dorian', 	  'Our mouse sensor delivers incredible accuracy, tracking speed and consistency for better control no matter your style of gameplay. Mouse can be used directly out-of-the-box.', 'assets/images/products/mice/mice-1004.png', 1, 130, 12.99, 4, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MICE-1005', 'Mice - Columbia',    'Our mouse sensor delivers incredible accuracy, tracking speed and consistency for better control no matter your style of gameplay. Mouse can be used directly out-of-the-box.', 'assets/images/products/mice/mice-1005.png', 1, 008, 13.99, 4, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MICE-1006', 'Mice - Worthing',    'Our mouse sensor delivers incredible accuracy, tracking speed and consistency for better control no matter your style of gameplay. Mouse can be used directly out-of-the-box.', 'assets/images/products/mice/mice-1006.png', 1, 230, 11.99, 4, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MICE-1007', 'Mice - Oak Cliff',   'Our mouse sensor delivers incredible accuracy, tracking speed and consistency for better control no matter your style of gameplay. Mouse can be used directly out-of-the-box.', 'assets/images/products/mice/mice-1007.png', 1, 102, 12.99, 4, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MICE-1008', 'Mice - Tachyon', 	  'Our mouse sensor delivers incredible accuracy, tracking speed and consistency for better control no matter your style of gameplay. Mouse can be used directly out-of-the-box.', 'assets/images/products/mice/mice-1008.png', 1, 103, 13.99, 4, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MICE-1009', 'Mice - Pan', 		  'Our mouse sensor delivers incredible accuracy, tracking speed and consistency for better control no matter your style of gameplay. Mouse can be used directly out-of-the-box.', 'assets/images/products/mice/mice-1009.png', 1, 004, 15.99, 4, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MICE-1010', 'Mice - Phase', 	  'Our mouse sensor delivers incredible accuracy, tracking speed and consistency for better control no matter your style of gameplay. Mouse can be used directly out-of-the-box.', 'assets/images/products/mice/mice-1010.png', 1, 104, 12.99, 4, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MICE-1011', 'Mice - Falling', 	  'Our mouse sensor delivers incredible accuracy, tracking speed and consistency for better control no matter your style of gameplay. Mouse can be used directly out-of-the-box.', 'assets/images/products/mice/mice-1011.png', 1, 150, 15.99, 4, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MICE-1012', 'Mice - Wispy', 	  'Our mouse sensor delivers incredible accuracy, tracking speed and consistency for better control no matter your style of gameplay. Mouse can be used directly out-of-the-box.', 'assets/images/products/mice/mice-1012.png', 1, 004, 12.99, 4, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MICE-1013', 'Mice - Arlington',   'Our mouse sensor delivers incredible accuracy, tracking speed and consistency for better control no matter your style of gameplay. Mouse can be used directly out-of-the-box.', 'assets/images/products/mice/mice-1013.png', 1, 105, 15.99, 4, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MICE-1014', 'Mice - Gazing', 	  'Our mouse sensor delivers incredible accuracy, tracking speed and consistency for better control no matter your style of gameplay. Mouse can be used directly out-of-the-box.', 'assets/images/products/mice/mice-1014.png', 1, 103, 13.99, 4, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MICE-1015', 'Mice - Azura', 	  'Our mouse sensor delivers incredible accuracy, tracking speed and consistency for better control no matter your style of gameplay. Mouse can be used directly out-of-the-box.', 'assets/images/products/mice/mice-1015.png', 1, 102, 13.99, 4, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MICE-1016', 'Mice - Quantum', 	  'Our mouse sensor delivers incredible accuracy, tracking speed and consistency for better control no matter your style of gameplay. Mouse can be used directly out-of-the-box.', 'assets/images/products/mice/mice-1016.png', 1, 004, 13.99, 4, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MICE-1017', 'Mice - LightYear',   'Our mouse sensor delivers incredible accuracy, tracking speed and consistency for better control no matter your style of gameplay. Mouse can be used directly out-of-the-box.', 'assets/images/products/mice/mice-1017.png', 1, 102, 13.99, 4, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MICE-1018', 'Mice - Taylor', 	  'Our mouse sensor delivers incredible accuracy, tracking speed and consistency for better control no matter your style of gameplay. Mouse can be used directly out-of-the-box.', 'assets/images/products/mice/mice-1018.png', 1, 105, 10.99, 4, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MICE-1019', 'Mice - Gracia', 	  'Our mouse sensor delivers incredible accuracy, tracking speed and consistency for better control no matter your style of gameplay. Mouse can be used directly out-of-the-box.', 'assets/images/products/mice/mice-1019.png', 1, 104, 16.99, 4, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MICE-1020', 'Mice - Relax', 	  'Our mouse sensor delivers incredible accuracy, tracking speed and consistency for better control no matter your style of gameplay. Mouse can be used directly out-of-the-box.', 'assets/images/products/mice/mice-1020.png', 1, 003, 14.99, 4, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MICE-1021', 'Mice - Windermer',   'Our mouse sensor delivers incredible accuracy, tracking speed and consistency for better control no matter your style of gameplay. Mouse can be used directly out-of-the-box.', 'assets/images/products/mice/mice-1021.png', 1, 102, 13.99, 4, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MICE-1022', 'Mice - Prancer', 	  'Our mouse sensor delivers incredible accuracy, tracking speed and consistency for better control no matter your style of gameplay. Mouse can be used directly out-of-the-box.', 'assets/images/products/mice/mice-1022.png', 1, 104, 12.99, 4, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MICE-1023', 'Mice - Recursion',   'Our mouse sensor delivers incredible accuracy, tracking speed and consistency for better control no matter your style of gameplay. Mouse can be used directly out-of-the-box.', 'assets/images/products/mice/mice-1023.png', 1, 005, 15.99, 4, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MICE-1024', 'Mice - Treasure',    'Our mouse sensor delivers incredible accuracy, tracking speed and consistency for better control no matter your style of gameplay. Mouse can be used directly out-of-the-box.', 'assets/images/products/mice/mice-1024.png', 1, 034, 12.99, 4, NOW());


-- -----------------------------------------------------
-- Monitors
-- -----------------------------------------------------
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MONITOR-1000', 'Monitor - Express', 	  'Our 20-inch desktop monitor can be used as a good secondary display for your laptop. Our monitor offers HD+ 1600x900 pixels resolution and HD ready with 1366 x 768 pixels resolution.', 'assets/images/products/monitors/monitor-1000.png', 1, 210, 120, 5, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MONITOR-1001', 'Monitor - Cherokee',	  'Our 20-inch desktop monitor can be used as a good secondary display for your laptop. Our monitor offers HD+ 1600x900 pixels resolution and HD ready with 1366 x 768 pixels resolution.', 'assets/images/products/monitors/monitor-1001.png', 1, 005, 130, 5, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MONITOR-1002', 'Monitor - Sweeper', 	  'Our 20-inch desktop monitor can be used as a good secondary display for your laptop. Our monitor offers HD+ 1600x900 pixels resolution and HD ready with 1366 x 768 pixels resolution.', 'assets/images/products/monitors/monitor-1002.png', 1, 009, 120, 5, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MONITOR-1003', 'Monitor - Aspire', 	  	  'Our 20-inch desktop monitor can be used as a good secondary display for your laptop. Our monitor offers HD+ 1600x900 pixels resolution and HD ready with 1366 x 768 pixels resolution.', 'assets/images/products/monitors/monitor-1003.png', 1, 104, 140, 5, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MONITOR-1004', 'Monitor - Dorian', 	  	  'Our 20-inch desktop monitor can be used as a good secondary display for your laptop. Our monitor offers HD+ 1600x900 pixels resolution and HD ready with 1366 x 768 pixels resolution.', 'assets/images/products/monitors/monitor-1004.png', 1, 130, 120, 5, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MONITOR-1005', 'Monitor - Columbia',      'Our 20-inch desktop monitor can be used as a good secondary display for your laptop. Our monitor offers HD+ 1600x900 pixels resolution and HD ready with 1366 x 768 pixels resolution.', 'assets/images/products/monitors/monitor-1005.png', 1, 008, 130, 5, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MONITOR-1006', 'Monitor - Worthing',      'Our 20-inch desktop monitor can be used as a good secondary display for your laptop. Our monitor offers HD+ 1600x900 pixels resolution and HD ready with 1366 x 768 pixels resolution.', 'assets/images/products/monitors/monitor-1006.png', 1, 230, 110, 5, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MONITOR-1007', 'Monitor - Oak Cliff',     'Our 20-inch desktop monitor can be used as a good secondary display for your laptop. Our monitor offers HD+ 1600x900 pixels resolution and HD ready with 1366 x 768 pixels resolution.', 'assets/images/products/monitors/monitor-1007.png', 1, 102, 120, 5, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MONITOR-1008', 'Monitor - Tachyon', 	  'Our 20-inch desktop monitor can be used as a good secondary display for your laptop. Our monitor offers HD+ 1600x900 pixels resolution and HD ready with 1366 x 768 pixels resolution.', 'assets/images/products/monitors/monitor-1008.png', 1, 103, 130, 5, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MONITOR-1009', 'Monitor - Pan', 		  'Our 20-inch desktop monitor can be used as a good secondary display for your laptop. Our monitor offers HD+ 1600x900 pixels resolution and HD ready with 1366 x 768 pixels resolution.', 'assets/images/products/monitors/monitor-1009.png', 1, 004, 150, 5, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MONITOR-1010', 'Monitor - Phase', 	      'Our 20-inch desktop monitor can be used as a good secondary display for your laptop. Our monitor offers HD+ 1600x900 pixels resolution and HD ready with 1366 x 768 pixels resolution.', 'assets/images/products/monitors/monitor-1010.png', 1, 104, 120, 5, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MONITOR-1011', 'Monitor - Falling', 	  'Our 20-inch desktop monitor can be used as a good secondary display for your laptop. Our monitor offers HD+ 1600x900 pixels resolution and HD ready with 1366 x 768 pixels resolution.', 'assets/images/products/monitors/monitor-1011.png', 1, 150, 150, 5, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MONITOR-1012', 'Monitor - Wispy', 		  'Our 20-inch desktop monitor can be used as a good secondary display for your laptop. Our monitor offers HD+ 1600x900 pixels resolution and HD ready with 1366 x 768 pixels resolution.', 'assets/images/products/monitors/monitor-1012.png', 1, 004, 120, 5, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MONITOR-1013', 'Monitor - Arlington',     'Our 20-inch desktop monitor can be used as a good secondary display for your laptop. Our monitor offers HD+ 1600x900 pixels resolution and HD ready with 1366 x 768 pixels resolution.', 'assets/images/products/monitors/monitor-1013.png', 1, 105, 150, 5, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MONITOR-1014', 'Monitor - Gazing', 	  	  'Our 20-inch desktop monitor can be used as a good secondary display for your laptop. Our monitor offers HD+ 1600x900 pixels resolution and HD ready with 1366 x 768 pixels resolution.', 'assets/images/products/monitors/monitor-1014.png', 1, 103, 130, 5, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MONITOR-1015', 'Monitor - Azura', 	  	  'Our 20-inch desktop monitor can be used as a good secondary display for your laptop. Our monitor offers HD+ 1600x900 pixels resolution and HD ready with 1366 x 768 pixels resolution.', 'assets/images/products/monitors/monitor-1015.png', 1, 102, 130, 5, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MONITOR-1016', 'Monitor - Quantum', 	  'Our 20-inch desktop monitor can be used as a good secondary display for your laptop. Our monitor offers HD+ 1600x900 pixels resolution and HD ready with 1366 x 768 pixels resolution.', 'assets/images/products/monitors/monitor-1016.png', 1, 004, 130, 5, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MONITOR-1017', 'Monitor - LightYear',     'Our 20-inch desktop monitor can be used as a good secondary display for your laptop. Our monitor offers HD+ 1600x900 pixels resolution and HD ready with 1366 x 768 pixels resolution.', 'assets/images/products/monitors/monitor-1017.png', 1, 102, 130, 5, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MONITOR-1018', 'Monitor - Taylor', 	      'Our 20-inch desktop monitor can be used as a good secondary display for your laptop. Our monitor offers HD+ 1600x900 pixels resolution and HD ready with 1366 x 768 pixels resolution.', 'assets/images/products/monitors/monitor-1018.png', 1, 105, 100, 5, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MONITOR-1019', 'Monitor - Gracia', 	      'Our 20-inch desktop monitor can be used as a good secondary display for your laptop. Our monitor offers HD+ 1600x900 pixels resolution and HD ready with 1366 x 768 pixels resolution.', 'assets/images/products/monitors/monitor-1019.png', 1, 104, 160, 5, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MONITOR-1020', 'Monitor - Relax', 	      'Our 20-inch desktop monitor can be used as a good secondary display for your laptop. Our monitor offers HD+ 1600x900 pixels resolution and HD ready with 1366 x 768 pixels resolution.', 'assets/images/products/monitors/monitor-1020.png', 1, 003, 140, 5, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MONITOR-1021', 'Monitor - Windermer',     'Our 20-inch desktop monitor can be used as a good secondary display for your laptop. Our monitor offers HD+ 1600x900 pixels resolution and HD ready with 1366 x 768 pixels resolution.', 'assets/images/products/monitors/monitor-1021.png', 1, 102, 130, 5, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MONITOR-1022', 'Monitor - Prancer', 	  'Our 20-inch desktop monitor can be used as a good secondary display for your laptop. Our monitor offers HD+ 1600x900 pixels resolution and HD ready with 1366 x 768 pixels resolution.', 'assets/images/products/monitors/monitor-1022.png', 1, 104, 120, 5, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MONITOR-1023', 'Monitor - Recursion',     'Our 20-inch desktop monitor can be used as a good secondary display for your laptop. Our monitor offers HD+ 1600x900 pixels resolution and HD ready with 1366 x 768 pixels resolution.', 'assets/images/products/monitors/monitor-1023.png', 1, 005, 150, 5, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('MONITOR-1024', 'Monitor - Treasure',      'Our 20-inch desktop monitor can be used as a good secondary display for your laptop. Our monitor offers HD+ 1600x900 pixels resolution and HD ready with 1366 x 768 pixels resolution.', 'assets/images/products/monitors/monitor-1024.png', 1, 034, 120, 5, NOW());


-- -----------------------------------------------------
-- Printers
-- -----------------------------------------------------
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('PRINTER-1000', 'Printer - Express', 	  'Our compact multifunctional printer offers more features than most other printers in this price range. Apart from high quality printing, you can use it for your copy and scan jobs too.', 'assets/images/products/printers/printer-1000.png', 1, 210, 120, 6, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('PRINTER-1001', 'Printer - Cherokee',	  'Our compact multifunctional printer offers more features than most other printers in this price range. Apart from high quality printing, you can use it for your copy and scan jobs too.', 'assets/images/products/printers/printer-1001.png', 1, 005, 130, 6, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('PRINTER-1002', 'Printer - Sweeper', 	  'Our compact multifunctional printer offers more features than most other printers in this price range. Apart from high quality printing, you can use it for your copy and scan jobs too.', 'assets/images/products/printers/printer-1002.png', 1, 009, 120, 6, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('PRINTER-1003', 'Printer - Aspire', 	  	  'Our compact multifunctional printer offers more features than most other printers in this price range. Apart from high quality printing, you can use it for your copy and scan jobs too.', 'assets/images/products/printers/printer-1003.png', 1, 104, 140, 6, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('PRINTER-1004', 'Printer - Dorian', 	  	  'Our compact multifunctional printer offers more features than most other printers in this price range. Apart from high quality printing, you can use it for your copy and scan jobs too.', 'assets/images/products/printers/printer-1004.png', 1, 130, 120, 6, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('PRINTER-1005', 'Printer - Columbia',      'Our compact multifunctional printer offers more features than most other printers in this price range. Apart from high quality printing, you can use it for your copy and scan jobs too.', 'assets/images/products/printers/printer-1005.png', 1, 008, 130, 6, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('PRINTER-1006', 'Printer - Worthing',      'Our compact multifunctional printer offers more features than most other printers in this price range. Apart from high quality printing, you can use it for your copy and scan jobs too.', 'assets/images/products/printers/printer-1006.png', 1, 230, 110, 6, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('PRINTER-1007', 'Printer - Oak Cliff',     'Our compact multifunctional printer offers more features than most other printers in this price range. Apart from high quality printing, you can use it for your copy and scan jobs too.', 'assets/images/products/printers/printer-1007.png', 1, 102, 120, 6, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('PRINTER-1008', 'Printer - Tachyon', 	  'Our compact multifunctional printer offers more features than most other printers in this price range. Apart from high quality printing, you can use it for your copy and scan jobs too.', 'assets/images/products/printers/printer-1008.png', 1, 103, 130, 6, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('PRINTER-1009', 'Printer - Pan', 		  'Our compact multifunctional printer offers more features than most other printers in this price range. Apart from high quality printing, you can use it for your copy and scan jobs too.', 'assets/images/products/printers/printer-1009.png', 1, 004, 150, 6, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('PRINTER-1010', 'Printer - Phase', 	      'Our compact multifunctional printer offers more features than most other printers in this price range. Apart from high quality printing, you can use it for your copy and scan jobs too.', 'assets/images/products/printers/printer-1010.png', 1, 104, 120, 6, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('PRINTER-1011', 'Printer - Falling', 	  'Our compact multifunctional printer offers more features than most other printers in this price range. Apart from high quality printing, you can use it for your copy and scan jobs too.', 'assets/images/products/printers/printer-1011.png', 1, 150, 150, 6, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('PRINTER-1012', 'Printer - Wispy', 		  'Our compact multifunctional printer offers more features than most other printers in this price range. Apart from high quality printing, you can use it for your copy and scan jobs too.', 'assets/images/products/printers/printer-1012.png', 1, 004, 120, 6, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('PRINTER-1013', 'Printer - Arlington',     'Our compact multifunctional printer offers more features than most other printers in this price range. Apart from high quality printing, you can use it for your copy and scan jobs too.', 'assets/images/products/printers/printer-1013.png', 1, 105, 150, 6, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('PRINTER-1014', 'Printer - Gazing', 	  	  'Our compact multifunctional printer offers more features than most other printers in this price range. Apart from high quality printing, you can use it for your copy and scan jobs too.', 'assets/images/products/printers/printer-1014.png', 1, 103, 130, 6, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('PRINTER-1015', 'Printer - Azura', 	  	  'Our compact multifunctional printer offers more features than most other printers in this price range. Apart from high quality printing, you can use it for your copy and scan jobs too.', 'assets/images/products/printers/printer-1015.png', 1, 102, 130, 6, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('PRINTER-1016', 'Printer - Quantum', 	  'Our compact multifunctional printer offers more features than most other printers in this price range. Apart from high quality printing, you can use it for your copy and scan jobs too.', 'assets/images/products/printers/printer-1016.png', 1, 004, 130, 6, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('PRINTER-1017', 'Printer - LightYear',     'Our compact multifunctional printer offers more features than most other printers in this price range. Apart from high quality printing, you can use it for your copy and scan jobs too.', 'assets/images/products/printers/printer-1017.png', 1, 102, 130, 6, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('PRINTER-1018', 'Printer - Taylor', 	      'Our compact multifunctional printer offers more features than most other printers in this price range. Apart from high quality printing, you can use it for your copy and scan jobs too.', 'assets/images/products/printers/printer-1018.png', 1, 105, 100, 6, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('PRINTER-1019', 'Printer - Gracia', 	      'Our compact multifunctional printer offers more features than most other printers in this price range. Apart from high quality printing, you can use it for your copy and scan jobs too.', 'assets/images/products/printers/printer-1019.png', 1, 104, 160, 6, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('PRINTER-1020', 'Printer - Relax', 	      'Our compact multifunctional printer offers more features than most other printers in this price range. Apart from high quality printing, you can use it for your copy and scan jobs too.', 'assets/images/products/printers/printer-1020.png', 1, 003, 140, 6, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('PRINTER-1021', 'Printer - Windermer',     'Our compact multifunctional printer offers more features than most other printers in this price range. Apart from high quality printing, you can use it for your copy and scan jobs too.', 'assets/images/products/printers/printer-1021.png', 1, 102, 130, 6, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('PRINTER-1022', 'Printer - Prancer', 	  'Our compact multifunctional printer offers more features than most other printers in this price range. Apart from high quality printing, you can use it for your copy and scan jobs too.', 'assets/images/products/printers/printer-1022.png', 1, 104, 120, 6, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('PRINTER-1023', 'Printer - Recursion',     'Our compact multifunctional printer offers more features than most other printers in this price range. Apart from high quality printing, you can use it for your copy and scan jobs too.', 'assets/images/products/printers/printer-1023.png', 1, 005, 150, 6, NOW());
INSERT INTO  product (SKU, NAME, DESCRIPTION, IMAGE_URL, ACTIVE, UNITS_IN_STOCK, UNIT_PRICE, CATEGORY_ID,DATE_CREATED) VALUES ('PRINTER-1024', 'Printer - Treasure',      'Our compact multifunctional printer offers more features than most other printers in this price range. Apart from high quality printing, you can use it for your copy and scan jobs too.', 'assets/images/products/printers/printer-1024.png', 1, 034, 120, 6, NOW());

